Repository googleapis/java-retail, pull requests merged in 2020-12, with the labels that each got.

#13 chore(deps): fix declared dependencies test
  grpc-google-cloud-retail-v2/pom.xml
Labels: cla: yes

#14 chore: regenerate common templates
  .github/generated-files-bot.yml
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  .github/workflows/ci.yaml
  .github/workflows/samples.yaml
  .kokoro/build.bat
  codecov.yaml
  synth.metadata
Labels: cla: yes, context: partial

#15 chore: update gapic-generator-java to 0.0.11
  google-cloud-retail/src/test/java/com/google/cloud/retail/v2/CatalogServiceClientTest.java
  proto-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/CatalogName.java
  synth.metadata
Labels: cla: yes, context: full

#16 chore: remove formatter action
  .github/workflows/formatting.yaml
Labels: cla: yes
