Repository googleapis/java-retail, pull requests merged in 2021-05, with the labels that each got.

#101 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: retail, automerge, cla: yes, context: none

#102 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: retail, automerge, cla: yes

#103 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: retail, automerge, cla: yes, context: full

#105 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: retail, automerge, cla: yes, context: full

#109 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: retail, automerge, cla: yes, context: full

#110 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: retail, automerge, cla: yes

#112 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: retail, automerge, cla: yes, context: full

#115 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: retail, automerge, cla: yes, context: full

#118 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: retail, automerge, cla: yes
