Repository googleapis/java-retail, pull requests merged in 2021-09, with the labels that each got.

#194 build(java): update renovate config to mark conformance tests as a test commit type
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full, api: retail

#197 chore(java): install maven 3.8.1 at runtime
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, kokoro:force-run, cla: yes, context: full, api: retail

#199 chore(java): update windows build
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, context: full, api: retail

#196 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  README.md
  google-cloud-retail-bom/pom.xml
  google-cloud-retail/pom.xml
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/CatalogServiceClient.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/CompletionServiceClient.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/ProductServiceClient.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/SearchServiceClient.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/package-info.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/CatalogServiceStubSettings.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/CompletionServiceStubSettings.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/PredictionServiceStubSettings.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/ProductServiceStubSettings.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/SearchServiceStubSettings.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/UserEventServiceStubSettings.java
  grpc-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/CatalogServiceGrpc.java
  grpc-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/CompletionServiceGrpc.java
  grpc-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/ProductServiceGrpc.java
  grpc-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/SearchServiceGrpc.java
  owlbot.py
  pom.xml
  proto-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/CompleteQueryRequest.java
  proto-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/CompleteQueryRequestOrBuilder.java
  proto-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/CompleteQueryResponse.java
  proto-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/CompleteQueryResponseOrBuilder.java
  proto-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/CompletionDataInputConfig.java
  proto-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/CompletionDataInputConfigOrBuilder.java
  proto-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/ImportProductsRequest.java
  proto-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/Product.java
  proto-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/ProductDetail.java
  proto-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/ProductDetailOrBuilder.java
  proto-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/ProductOrBuilder.java
  proto-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/SearchRequest.java
  proto-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/SearchRequestOrBuilder.java
  proto-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/SearchResponse.java
  proto-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/SearchServiceProto.java
  proto-google-cloud-retail-v2/src/main/proto/google/cloud/retail/v2/catalog.proto
  proto-google-cloud-retail-v2/src/main/proto/google/cloud/retail/v2/catalog_service.proto
  proto-google-cloud-retail-v2/src/main/proto/google/cloud/retail/v2/common.proto
  proto-google-cloud-retail-v2/src/main/proto/google/cloud/retail/v2/completion_service.proto
  proto-google-cloud-retail-v2/src/main/proto/google/cloud/retail/v2/import_config.proto
  proto-google-cloud-retail-v2/src/main/proto/google/cloud/retail/v2/prediction_service.proto
  proto-google-cloud-retail-v2/src/main/proto/google/cloud/retail/v2/product.proto
  proto-google-cloud-retail-v2/src/main/proto/google/cloud/retail/v2/product_service.proto
  proto-google-cloud-retail-v2/src/main/proto/google/cloud/retail/v2/purge_config.proto
  proto-google-cloud-retail-v2/src/main/proto/google/cloud/retail/v2/search_service.proto
  proto-google-cloud-retail-v2/src/main/proto/google/cloud/retail/v2/user_event.proto
  proto-google-cloud-retail-v2/src/main/proto/google/cloud/retail/v2/user_event_service.proto
  synth.py
  versions.txt
Labels: automerge, cla: yes, api: retail

#201 chore: remove readme autosynth config
  .github/.OwlBot.lock.yaml
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .github/trusted-contribution.yml
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
Labels: automerge, cla: yes, api: retail

#212 chore: make owlbot check required
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: retail

#214 chore: remove readme autosynth config
  .kokoro/continuous/readme.cfg
Labels: automerge, cla: yes, api: retail

#209 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: automerge, cla: yes, api: retail

#221 chore: change branch master to main in github configurations
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: retail
