Repository googleapis/java-retail, pull requests merged in 2021-08, with the labels that each got.

#163 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: retail, automerge, cla: yes

#151 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full, api: retail

#164 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: retail

#159 docs: remove remaining private links
  proto-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/SearchRequest.java
  proto-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/SearchRequestOrBuilder.java
  proto-google-cloud-retail-v2/src/main/proto/google/cloud/retail/v2/search_service.proto
  synth.metadata
Labels: cla: yes, context: full, api: retail

#165 chore: remove java7 units check from required checks in master
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: retail

#169 feat!: release gapic-generator-java v2.0.0
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/CatalogServiceClient.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/CatalogServiceSettings.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/CompletionServiceSettings.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/PredictionServiceSettings.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/ProductServiceClient.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/ProductServiceSettings.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/SearchServiceClient.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/SearchServiceSettings.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/UserEventServiceSettings.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/CatalogServiceStubSettings.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/CompletionServiceStubSettings.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/GrpcCatalogServiceStub.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/GrpcCompletionServiceStub.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/GrpcPredictionServiceStub.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/GrpcProductServiceStub.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/GrpcSearchServiceStub.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/GrpcUserEventServiceStub.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/PredictionServiceStubSettings.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/ProductServiceStubSettings.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/SearchServiceStubSettings.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/UserEventServiceStubSettings.java
  proto-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/SearchRequest.java
  proto-google-cloud-retail-v2/src/main/java/com/google/cloud/retail/v2/SearchResponse.java
  proto-google-cloud-retail-v2/src/main/proto/google/cloud/retail/v2/search_service.proto
  synth.metadata
Labels: automerge, cla: yes, context: full, api: retail

#173 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: retail

#171 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full, api: retail

#176 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: retail

#179 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: retail

#185 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: retail

#184 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: retail

#187 ci: removing linkage-monitor from the required checks
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full, api: retail

#177 chore: update gapic-generator-java version to 2.1.0
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/CatalogServiceStubSettings.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/CompletionServiceStubSettings.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/PredictionServiceStubSettings.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/ProductServiceStubSettings.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/SearchServiceStubSettings.java
  google-cloud-retail/src/main/java/com/google/cloud/retail/v2/stub/UserEventServiceStubSettings.java
  synth.metadata
Labels: automerge, cla: yes, context: full, api: retail

#189 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: retail
